---
title: amanda grace – experience design
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    description:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description:
permalink: pretty
